### ISSUE TITLE
"The resource cannot be found" error on running 

### ISSUE THREAD

**Issue by sethreidnz** [microsoft/ado-npm-auth#11]
I've followed the instructions in the readme and when I run:

```
npm exec ado-npm-auth
```

I get the following error

```
undefined:1
The resource cannot be found.
^

SyntaxError: Unexpected token 'T', "The resour"... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/seth/dev/microsoft/azureserviceinsights/src/AzureServiceInsights/ClientApp/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38253:37)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

## System settings

- Node version - v20.10.0
- NPM version - 10.4.0
- OS - MacOS 14.4.1 (23E224)

**Comment by sethreidnz** [comment]
could be related to this as doing the skip check flag seemed to fix it

https://github.com/microsoft/ado-npm-auth/pull/5

**Comment by thsparks** [comment]
I'm also seeing the "AzureAuth is not installed." error when running on WSL:

```
🔑 Authenticating to package feed...
Encountered error while performing auth Error: AzureAuth is not installed.
    at adoPat (/home/<user>/.npm/_npx/db64d855fa186e0a/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38678:19)
    at async generateNpmrcPat (/home/<user>/.npm/_npx/db64d855fa186e0a/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38693:17)
    at async setNpmrcPat (/home/<user>/.npm/_npx/db64d855fa186e0a/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38817:51)
    at async run (/home/<user>/.npm/_npx/db64d855fa186e0a/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38130:9)
    at async /home/<user>/.npm/_npx/db64d855fa186e0a/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38153:16
❌ Authentication to package feed failed.
```

# System Settings
Node version - v18.20.4
Npm version - 10.7.0
WSL - 5.15.153.1
