### ISSUE TITLE
Support scoped registries

### ISSUE THREAD

**Issue by kwickramasekara** [microsoft/ado-npm-auth#36]
**Is your feature request related to a problem? Please describe.**
When scoped registries are present in the `.npmrc` file, ado-npm-auth ends up with the following error:
```bash
/Users/redacted/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38220
            throw new Error("Registry URL missing or invalid");
                  ^

Error: Registry URL missing or invalid
    at getRepoNpmrcAdoOrganizations (/Users/redacted/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38220:19)
    at async getNpmrcFeeds (/Users/redacted/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38446:30)
    at async isValidPat (/Users/redacted/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38426:19)
    at async run (/Users/redacted/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38120:26)
    at async /Users/redacted/node_modules/ado-npm-auth/dist/ado-npm-auth.cjs:38153:16
```

**Describe the solution you'd like**
When scoped registries are present, ado-npm-auth should obtain tokens for each registry. An example of such `.npmrc`:
```ini
@foo:registry=https://pkgs.dev.azure.com/foo/_packaging/foo-feed/npm/registry/
@bar:registry=https://pkgs.dev.azure.com/bar/_packaging/bar-feed/npm/registry/
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kwickramasekara** [comment]
NVM, this looks to be an issue with how we have ado-npm-auth set up. Closing for now.
